name: Build 2descent proposal

on:
  push:
    branches: ["main"]
    paths:
      - "tex/2descent_proposal/**"
      - ".github/workflows/build_2descent_proposal.yml"
      - ".latexmkrc"
  workflow_dispatch:

jobs:
  build-cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile 2descent proposal
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tex/2descent_proposal/main.tex
          work_in_root_file_dir: true
          args: -r ../.latexmkrc
          texlive_version: 2025
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: 2descent-pdf
          path: tex/2descent_proposal/main.pdf
          if-no-files-found: error
