name: Build Slides_particlegf

on:
  push:
    branches: ["main"]
    paths:
      - "tex/Slides_particlegf/**"
      - ".github/workflows/build_slides_particlegf.yml"
      - ".latexmkrc"
  workflow_dispatch:

jobs:
  build-sliding-ricci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Slides_particlegf
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tex/Slides_particlegf/main.tex
          work_in_root_file_dir: true
          args: -r ../.latexmkrc
          texlive_version: 2025
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: slides-particlegf-pdf
          path: tex/Slides_particlegf/main.pdf
          if-no-files-found: error
