name: Build information_geometry

on:
  push:
    branches: ["main"]
    paths:
      - "tex/Information_Geometry/**"
      - ".github/workflows/build_info_geo.yml"
      - ".latexmkrc"
  workflow_dispatch:

jobs:
  build-info-geo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Information_Geometry
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tex/Information_Geometry/main.tex
          work_in_root_file_dir: true
          args: -r ../.latexmkrc
          texlive_version: 2025
          pre_compile: |
            tlmgr update --self
            tlmgr install subfiles
          latexmk_shell_escape: true   # leave true only if needed
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: info-geo-pdf
          path: tex/Information_Geometry/main.pdf
          if-no-files-found: error
