name: Build CV

on:
  push:
    branches: ["main"]
    paths:
      - "tex/cv/**"
      - ".github/workflows/build_cv.yml"
      - ".latexmkrc"
  workflow_dispatch:

jobs:
  build-cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tex/cv/cv.tex
          work_in_root_file_dir: true
          args: -r ../.latexmkrc
          texlive_version: 2025
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: tex/cv/cv.pdf
          if-no-files-found: error
